# Generated by Django 4.2.1 on 2023-06-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='menu')),
                ('tipo_plato', models.IntegerField(choices=[(0, 'Entrada'), (1, 'Principal'), (2, 'Postre'), (3, 'Liquidos')])),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
