# Generated by Django 4.2.1 on 2023-06-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_menu_contacto_asunto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Platos',
        ),
    ]
