# Generated by Django 4.2.1 on 2023-06-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_rename_menu_platos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='imagen',
            field=models.ImageField(upload_to='platos'),
        ),
    ]
