# Generated by Django 4.2.2 on 2023-06-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
