# Generated by Django 4.2.2 on 2023-06-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'No Disponible')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='producto'),
        ),
    ]
