# Generated by Django 4.2.2 on 2023-06-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_producto_disponible_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='origen',
            field=models.IntegerField(choices=[(0, 'Propio'), (1, 'Proveedor Externo')], default=0),
            preserve_default=False,
        ),
    ]
