# Generated by Django 4.2.2 on 2023-06-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0011_producto_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidadVendidos',
            field=models.IntegerField(default=0),
        ),
    ]
