# Generated by Django 4.2.2 on 2023-06-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0014_cartitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total',
            new_name='total_carrito',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_item',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
