# Generated by Django 4.2.2 on 2023-06-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0016_usuarioempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioempresa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='usuarioempresa',
            name='telefono',
        ),
    ]
