# Generated by Django 4.2.2 on 2023-07-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0019_rename_programado_semanalmente_pedido_programar_semanalmente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='programar_semanalmente',
            new_name='programar_diariamente',
        ),
    ]
