# Generated by Django 4.2.2 on 2023-07-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0020_rename_programar_semanalmente_pedido_programar_diariamente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(),
        ),
    ]
