# Generated by Django 4.2.2 on 2023-07-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0021_alter_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Entregado')], default=0),
        ),
    ]
