# Generated by Django 4.2.2 on 2023-07-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0022_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Entregado'), (2, 'Cancelado')], default=0),
        ),
    ]
