# Generated by Django 4.2.2 on 2023-07-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0023_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Activo'), (1, 'Desactivado')], default=0),
        ),
    ]
