# Generated by Django 4.2.2 on 2023-07-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0024_usuarioempresa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En Camino'), (2, 'Cancelado'), (3, 'Entregado')], default=0),
        ),
    ]
