# Generated by Django 4.2.2 on 2023-07-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0027_remove_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalle_pedido',
            field=models.ManyToManyField(to='appweb.cartitem'),
        ),
    ]
